# in configuration.yaml:
# mqtt: !include sol.yaml
# in sol.yaml inhalt:
sensor:
  - name: "SolMateInjectPower"
    unique_id: "solinjectpower"
    state_topic: "eet/solmate/0/inject_power"
    suggested_display_precision: 0
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
  - name: "SolMateTemperature"
    unique_id: "soltemp"
    state_topic: "eet/solmate/0/temperature"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
  - name: "Solmate Battery"
    unique_id: "solmatebattery"
    state_topic: "eet/solmate/0/battery_state"
    value_template: "{{ value | multiply(100) | round(0) }}"
    suggested_display_precision: 2
    unit_of_measurement: "%"
    device_class: "battery"
    state_class: "measurement"
  - name: "SolMatePVLeistung"
    unique_id: "solmatepvLeistung"
    state_topic: "eet/solmate/0/pv_power"
    suggested_display_precision: 0
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
  - name: "SolBattery_flow"
    unique_id: "solbatteryflow"
    state_topic: "eet/solmate/0/battery_flow"
    suggested_display_precision: 2
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
  - name: "SolBattery_Laden"
    unique_id: "solbatteryin"
    state_topic: "eet/solmate/0/battery_in"
    suggested_display_precision: 1
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
  - name: "SolBattery_Liefern"
    unique_id: "solbatteryout"
    state_topic: "eet/solmate/0/battery_out"
    suggested_display_precision: 1
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
  - name: "SolSettings_user_minimum_injection"
    unique_id: "solsetmininjection"
    state_topic: "eet/solmate/0/user_minimum_injection"
    suggested_display_precision: 0
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
  - name: "SolSettings_user_maximum_injection"
    unique_id: "solsetmaxinjection"
    state_topic: "eet/solmate/0/user_maximum_injection"
    suggested_display_precision: 0
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
  - name: "SolSettings_user_minimum_battery_percentage"
    unique_id: "solsetminbatpercentage"
    state_topic: "eet/solmate/0/user_minimum_battery_percentage"
    suggested_display_precision: 0
    unit_of_measurement: "%"
    device_class: "battery"
    state_class: "measurement"
  - name: "SolApiUptime"
    unique_id: "solapiuptime"
    state_topic: "eet/solmate/0/uptime"
    device_class: timestamp
  # - name: "SolApiLastSeen"
  #   unique_id: "solapilastseen"
  #   state_topic: "eet/solmate/0/last_seen"
  #   device_class: timestamp
